import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const sectors = [
  {
    slug: 'klinik',
    name: 'Klinik & Sağlık',
    tagline: 'Klinik, poliklinik, diş hekimi, fizyoterapi ve estetik merkezleri için tam dijital çözüm.',
    heroBadge: 'Sağlık Sektörü Çözümü',
    heroTitle: 'Klinik yönetimini\nbaştan sona dijitalleştirin',
    heroSubtitle: 'Hasta dosyası, randevu, e-Reçete, MHRS, laboratuvar entegrasyonu, SGK provizyon — tek panelde toplayın. Hastanız mutlu, ekibiniz hızlı, kasanız güvende.',
    icon: 'Stethoscope',
    iconColor: '#dc2626',
    bgColor: '#fef2f2',
    problems: [
      { title: 'Randevular telefonla, defterde takip ediliyor', description: 'Çift randevu, unutulan hatırlatma, boş slot — günde saatler kayıp.', icon: 'PhoneOff' },
      { title: 'Hasta dosyaları kağıtta veya farklı sistemlerde', description: 'Geçmiş tedavi bilgisini bulmak 5-10 dakika alıyor.', icon: 'FileX' },
      { title: 'e-Reçete ve MHRS için ayrı ekran açmak zorundasınız', description: 'Aynı bilgiyi 3 yere ayrı ayrı girmek hata payını artırıyor.', icon: 'Repeat' },
      { title: 'SGK provizyon ve fatura takibi karışık', description: 'Reddedilen faturalar geç fark ediliyor, gelir kayboluyor.', icon: 'AlertTriangle' },
    ],
    features: [
      { title: 'Online Randevu & Otomatik Hatırlatma', description: 'Hasta web/WhatsApp\'tan randevu alır, SMS hatırlatma otomatik gider.', icon: 'CalendarCheck' },
      { title: 'Dijital Hasta Dosyası', description: 'Anamnez, tedavi planı, görsel, rapor — hepsi tek hasta kartında.', icon: 'FolderOpen' },
      { title: 'e-Reçete & e-Rapor Entegrasyonu', description: 'Sağlık Bakanlığı sistemleriyle tam entegre — tek tıkla yazılır.', icon: 'Pill' },
      { title: 'MHRS & SGK Provizyon', description: 'Otomatik provizyon, fatura takibi, ret nedenleri raporu.', icon: 'ShieldCheck' },
      { title: 'Laboratuvar & Görüntüleme Entegrasyonu', description: 'Tahlil ve görüntülemeler doğrudan hasta kartına düşer.', icon: 'TestTube' },
      { title: 'Online Ödeme & Kasa', description: 'POS, banka transferi, taksit takibi — muhasebe entegre.', icon: 'CreditCard' },
    ],
    benefits: [
      { label: 'Randevu işlemi hızı', value: '5×', description: 'Telefonla 4 dk, dijitalle 45 sn.' },
      { label: 'Boş slot oranı', value: '-%62', description: 'Otomatik hatırlatma ile gelmeyenler azalır.' },
      { label: 'Aylık zaman tasarrufu', value: '40+ saat', description: 'Sekreteryadan klinik yönetimine.' },
      { label: 'Hasta memnuniyeti', value: '+%38', description: 'Online randevu ve hızlı hizmet ile.' },
    ],
    modules: [
      { name: 'Randevu & Hatırlatma', description: 'Online rezervasyon, takvim, SMS/WhatsApp.' },
      { name: 'Hasta Dosyası (EHR)', description: 'Anamnez, tedavi planı, görsel arşiv.' },
      { name: 'e-Reçete / e-Rapor', description: 'Sağlık Bakanlığı entegre.' },
      { name: 'SGK Provizyon', description: 'Otomatik provizyon ve fatura.' },
      { name: 'Laboratuvar', description: 'Sonuçlar otomatik düşer.' },
      { name: 'Muhasebe & Kasa', description: 'POS, e-Fatura, gelir-gider.' },
    ],
    faqs: [
      { question: 'Mevcut hasta verilerimi taşıyabiliyor musunuz?', answer: 'Evet. Excel, eski yazılım veya kağıt kayıt — hepsini taşıyıp kontrol ediyoruz. Geçiş süresi 1-3 gün.' },
      { question: 'KVKK uyumlu mu? Hasta verileri güvende mi?', answer: 'Tamamen. KVKK uyumlu altyapı, şifreli yedekleme, rol-bazlı erişim. Yıllık ISO 27001 denetimli sunucu.' },
      { question: 'e-Reçete için ayrı sistem gerekir mi?', answer: 'Hayır. Sağlık Bakanlığı sistemleri tam entegre — tek ekrandan yazılır.' },
      { question: 'Birden fazla hekim çalışıyor, kullanıcı sınırı var mı?', answer: 'Yok. Paketinize göre 5-50+ kullanıcı tanımlayabilirsiniz, rol-bazlı yetki ile.' },
      { question: 'Kurulum ve eğitim ne kadar sürer?', answer: 'Ortalama 3-7 gün. Ekibinize uzaktan veya yerinde eğitim veriyoruz, ilk ay ücretsiz destek.' },
    ],
    ctaTitle: 'Kliniğinizi dijitalleştirelim',
    ctaSubtitle: '15 dakikalık ücretsiz keşif görüşmesi alın — kliniğinize özel demo gösterelim.',
    seoTitle: 'Klinik Yazılımı & Hasta Yönetim Sistemi | kooza',
    seoDescription: 'Klinik, poliklinik, diş hekimi için randevu, hasta dosyası, e-Reçete, MHRS, SGK provizyon — tek sistemde. Ücretsiz demo.',
    order: 1,
  },
  {
    slug: 'restoran',
    name: 'Restoran & Kafe',
    tagline: 'Adisyon, kasa, masa yönetimi, kurye entegrasyonu — restoran ve kafe için tam otomasyon.',
    heroBadge: 'Yeme-İçme Sektörü Çözümü',
    heroTitle: 'Restoran ve kafenizi\nakıllı şekilde yönetin',
    heroSubtitle: 'Adisyon, kasa, masa düzeni, mutfak ekranı, kurye entegrasyonu, sadakat programı — hepsi tek panelde. Müşteri sıra beklemez, mutfak şaşırmaz, kasa açığı kapanır.',
    icon: 'UtensilsCrossed',
    iconColor: '#ea580c',
    bgColor: '#fff7ed',
    problems: [
      { title: 'Adisyon defterde, kasada hata payı yüksek', description: 'Ay sonu açıklar, bahşiş karışıklığı, fişsiz satış.', icon: 'BookX' },
      { title: 'Mutfak ile servis arasında karışıklık', description: 'Yanlış sipariş, geciken yemekler, soğuyan tabaklar.', icon: 'AlertCircle' },
      { title: 'Kurye platformlarına ayrı ayrı sipariş giriliyor', description: 'Yemeksepeti + Getir + Trendyol Yemek için 3 ekran açık.', icon: 'Layers' },
      { title: 'Stok takibi yok — neyin azaldığını sonradan anlıyorsunuz', description: 'Servis sırasında biten malzeme, müşteri kaybı.', icon: 'PackageX' },
    ],
    features: [
      { title: 'Adisyon & Masa Yönetimi', description: 'Tablet/telefonla hızlı sipariş, masa transferi, bölme/birleştirme.', icon: 'Tablet' },
      { title: 'Mutfak Ekranı (KDS)', description: 'Sipariş otomatik mutfağa düşer, hazır olunca servisi uyarır.', icon: 'Monitor' },
      { title: 'Yemeksepeti / Getir / Trendyol Entegrasyonu', description: 'Tüm platformlardan gelen sipariş tek ekranda.', icon: 'Truck' },
      { title: 'Kasa & POS', description: 'Z raporu, gün sonu, vardiya yönetimi, e-Fatura.', icon: 'Calculator' },
      { title: 'Stok & Reçete', description: 'Her satışta otomatik stok düşer, kritik seviyede uyarır.', icon: 'Package' },
      { title: 'Sadakat & Kampanya', description: 'Müşteriye SMS/WhatsApp kampanya, puan sistemi.', icon: 'Gift' },
    ],
    benefits: [
      { label: 'Sipariş alma süresi', value: '3×', description: 'Tabletle 30 sn, defterle 1.5 dk.' },
      { label: 'Kasa açığı', value: '-%85', description: 'Otomatik fiş + denetim ile sıfıra yakın.' },
      { label: 'Kurye platform yönetimi', value: 'Tek ekran', description: '3 platforma ayrı bakmak yerine.' },
      { label: 'Aylık stok kaybı', value: '-%40', description: 'Reçete tabanlı stok takibi ile.' },
    ],
    modules: [
      { name: 'Adisyon (Tablet/Telefon)', description: 'Hızlı sipariş, masa yönetimi.' },
      { name: 'Mutfak Ekranı', description: 'Otomatik sipariş aktarımı.' },
      { name: 'Kurye Entegrasyonu', description: 'Yemeksepeti, Getir, Trendyol.' },
      { name: 'Kasa & e-Fatura', description: 'Gün sonu, vardiya, GİB uyumlu.' },
      { name: 'Stok & Reçete', description: 'Otomatik stok düşümü.' },
      { name: 'Sadakat Programı', description: 'Puan, kampanya, SMS.' },
    ],
    faqs: [
      { question: 'Mevcut yazıcı/POS\'umla çalışır mı?', answer: 'Evet. Termal yazıcı, POS, kasa çekmecesi, barkod okuyucu — tüm standart cihazlarla uyumlu.' },
      { question: 'Yemeksepeti dışındaki platformlarla da entegre mi?', answer: 'Yemeksepeti, Getir, Trendyol Yemek, MigrosYemek dahil tüm büyük platformlar entegre. Direkt site üzerinden online sipariş de alabilirsiniz.' },
      { question: 'İnternet kesilince çalışmaya devam eder mi?', answer: 'Evet. Adisyon ve kasa offline çalışır, internet gelince otomatik senkronize olur.' },
      { question: 'Birden fazla şubem var, hepsini tek panelden yönetebilir miyim?', answer: 'Evet. Şube bazlı raporlama, merkezi menü/fiyat yönetimi, transfer takibi.' },
    ],
    ctaTitle: 'Restoranınızı dijitalleştirelim',
    ctaSubtitle: 'Ücretsiz demo + ilk ay deneme sunuyoruz. 15 dakikalık görüşme yeter.',
    seoTitle: 'Restoran & Kafe Otomasyonu — Adisyon, Kasa, Kurye | kooza',
    seoDescription: 'Restoran ve kafe için adisyon, mutfak ekranı, Yemeksepeti/Getir/Trendyol entegrasyonu, kasa, stok, sadakat. Ücretsiz demo.',
    order: 2,
  },
  {
    slug: 'market',
    name: 'Market & Perakende',
    tagline: 'Market, bakkal, kuruyemiş, kozmetik gibi perakende noktaları için kasa-stok-zincir yönetimi.',
    heroBadge: 'Perakende Sektörü Çözümü',
    heroTitle: 'Market ve perakendenizde\nstok kayıplarına son',
    heroSubtitle: 'Barkod, kasa, stok, fiyat etiketi, sadakat — tek noktadan zincir yönetimi. Hangi ürün ne kadar satıyor, kasada eksik var mı, hangi şube kâr ediyor — anında bilin.',
    icon: 'ShoppingCart',
    iconColor: '#16a34a',
    bgColor: '#f0fdf4',
    problems: [
      { title: 'Stok takibi tahminle yapılıyor', description: 'Aylık fiziki sayımda büyük farklar, neyin satıldığı belirsiz.', icon: 'Search' },
      { title: 'Fiyat etiketi değişikliği el ile saatler alıyor', description: 'Kampanya başlatmak veya bitirmek bir mesai.', icon: 'Tag' },
      { title: 'Şube karşılaştırması yapamıyorsunuz', description: 'Hangi şube kârlı, hangi ürün hangi şubede satıyor — bilinmiyor.', icon: 'BarChart3' },
      { title: 'Sadakat müşterisi tutulamıyor', description: 'İndirim verdiğiniz halde geri gelmiyor, neden bilinmiyor.', icon: 'UserMinus' },
    ],
    features: [
      { title: 'Barkod & Hızlı Kasa', description: 'Saniyede 5+ ürün okutma, terazi entegrasyonu, e-Fatura.', icon: 'ScanBarcode' },
      { title: 'Akıllı Stok Yönetimi', description: 'Min/max seviye, otomatik sipariş önerisi, son kullanma takibi.', icon: 'Package' },
      { title: 'Etiket & Fiyat Yönetimi', description: 'Toplu fiyat değişikliği, kampanya programı, raf etiketi yazdırma.', icon: 'Tag' },
      { title: 'Çoklu Şube Yönetimi', description: 'Şube bazlı raporlama, merkezi stok transferi, performans karşılaştırma.', icon: 'Building' },
      { title: 'Sadakat & Müşteri Kart', description: 'Puan, indirim, doğum günü kampanyası, SMS hatırlatma.', icon: 'CreditCard' },
      { title: 'Tedarikçi & Sipariş', description: 'Tedarikçi kart, alım siparişi, irsaliye, e-Fatura kabul.', icon: 'Truck' },
    ],
    benefits: [
      { label: 'Stok kaybı', value: '-%55', description: 'Anlık takip ile fiziki sayımda fark azalır.' },
      { label: 'Kasa hızı', value: '2-3×', description: 'Barkodlu sistem ile sıra erir.' },
      { label: 'Aylık ek satış', value: '+%18', description: 'Sadakat + kampanya etkisi.' },
      { label: 'Etiket değişim süresi', value: '-%90', description: 'Saatlerden dakikalara.' },
    ],
    modules: [
      { name: 'Kasa & Barkod', description: 'Hızlı satış, e-Fatura.' },
      { name: 'Stok & Sayım', description: 'Otomatik takip, son kullanma.' },
      { name: 'Fiyat & Etiket', description: 'Toplu değişiklik, raf etiketi.' },
      { name: 'Çoklu Şube', description: 'Transfer, karşılaştırma.' },
      { name: 'Sadakat Kartı', description: 'Puan, kampanya, SMS.' },
      { name: 'Tedarikçi', description: 'Sipariş, irsaliye, e-Fatura.' },
    ],
    faqs: [
      { question: 'Mevcut barkod cihazım ve yazıcımla uyumlu mu?', answer: 'Evet. Tüm standart barkod okuyucu, termal yazıcı ve teraziler ile uyumlu.' },
      { question: 'Şubeler arası stok transferi nasıl?', answer: 'Tek tıkla irsaliye oluşur, karşı şube onaylar, stok otomatik geçer. Yolda transfer takibi de var.' },
      { question: 'e-Fatura gönderimi otomatik mi?', answer: 'Evet. GİB entegre — satış sonrası tek tıkla veya otomatik gönderim.' },
      { question: 'Tedarikçilerden e-Fatura kabul ediyor mu?', answer: 'Evet. Gelen e-Faturaları otomatik stok ve cari kayıtlarına işliyor.' },
    ],
    ctaTitle: 'Marketinizi dijitalleştirelim',
    ctaSubtitle: 'Tek şubeden zincire — büyüklüğünüze göre çözüm. Ücretsiz analiz.',
    seoTitle: 'Market & Perakende Yazılımı — Kasa, Stok, Sadakat | kooza',
    seoDescription: 'Market, bakkal, perakende için barkod, kasa, stok, çoklu şube, sadakat kartı, e-Fatura. Ücretsiz demo.',
    order: 3,
  },
  {
    slug: 'egitim',
    name: 'Eğitim & Kurs',
    tagline: 'Dershane, kurs, anaokulu, dil okulu, akademi için öğrenci yönetimi ve sınav sistemi.',
    heroBadge: 'Eğitim Sektörü Çözümü',
    heroTitle: 'Eğitim kurumunuzu\nuçtan uca yönetin',
    heroSubtitle: 'Öğrenci kayıt, ders programı, online sınav, devam takibi, veli portalı, taksit takibi — tek sistemde. Eğitmen öğretmeye, siz büyütmeye odaklanın.',
    icon: 'GraduationCap',
    iconColor: '#4f46e5',
    bgColor: '#eef2ff',
    problems: [
      { title: 'Öğrenci kaydı Excel\'de, taksitler defterde', description: 'Ödeme takip kabusu, alacak hesabı belirsiz.', icon: 'FileSpreadsheet' },
      { title: 'Veli ile iletişim WhatsApp grubunda', description: 'Önemli bilgiler kayboluyor, devam-not bilgisi alınamıyor.', icon: 'MessageSquareWarning' },
      { title: 'Sınav sonuçları geç hesaplanıyor', description: 'Optik okuma, manuel puanlama saatler alıyor.', icon: 'Clock' },
      { title: 'Ders programı çakışmaları', description: 'Eğitmen-derslik-öğrenci çakışmaları sürekli sorun.', icon: 'CalendarX' },
    ],
    features: [
      { title: 'Öğrenci & Veli Kart', description: 'Bilgi, dönem, taksit, devam, sınav — tek profilde.', icon: 'Users' },
      { title: 'Online Sınav & Otomatik Puanlama', description: 'Soru bankası, online çözüm, anında sonuç.', icon: 'FileCheck2' },
      { title: 'Ders Programı & Devam', description: 'Otomatik program, çakışma kontrolü, QR ile yoklama.', icon: 'CalendarCheck' },
      { title: 'Veli Portalı (Web + Mobil)', description: 'Veli kendi öğrencisini takip eder — devam, not, ödeme.', icon: 'Smartphone' },
      { title: 'Taksit & Tahsilat', description: 'Otomatik hatırlatma, online ödeme, alacak raporu.', icon: 'CreditCard' },
      { title: 'SMS/WhatsApp Bildirim', description: 'Sınav sonucu, devamsızlık, ödeme hatırlatma otomatik.', icon: 'MessageCircle' },
    ],
    benefits: [
      { label: 'Tahsilat oranı', value: '+%32', description: 'Otomatik hatırlatma ile gecikme azalır.' },
      { label: 'Sınav değerlendirme süresi', value: '-%95', description: 'Saatlerden saniyelere.' },
      { label: 'Veli memnuniyeti', value: '+%47', description: 'Şeffaf takip ile.' },
      { label: 'Yönetimsel zaman', value: '20+ saat/ay', description: 'Eğitime ayrılan zaman artar.' },
    ],
    modules: [
      { name: 'Öğrenci Kayıt', description: 'Profil, dönem, doküman.' },
      { name: 'Online Sınav', description: 'Soru bankası, otomatik puanlama.' },
      { name: 'Ders & Devam', description: 'Program, çakışma, QR yoklama.' },
      { name: 'Veli Portalı', description: 'Web ve mobil takip.' },
      { name: 'Taksit & Tahsilat', description: 'Online ödeme, hatırlatma.' },
      { name: 'CRM & Aday Takip', description: 'Lead\'den kayda dönüşüm.' },
    ],
    faqs: [
      { question: 'Mevcut öğrenci verilerimi taşıyabilir misiniz?', answer: 'Evet. Excel veya eski yazılım — tüm verileri kontrolden geçirip taşıyoruz.' },
      { question: 'Online sınav nasıl çalışıyor?', answer: 'Öğrenci link/QR ile girer, soruları çözer, sistem otomatik puanlar. Optik okuma da var.' },
      { question: 'Veli portalı ücretsiz mi?', answer: 'Evet. Veli portalı ve mobil uygulama paket fiyatına dahil — ekstra ücret yok.' },
      { question: 'Birden fazla şubem var, yönetebilir miyim?', answer: 'Evet. Şube bazlı yönetim, merkezi raporlama, eğitmen havuzu.' },
    ],
    ctaTitle: 'Eğitim kurumunuzu dijitalleştirelim',
    ctaSubtitle: 'Ücretsiz demo + ilk ay deneme. Anaokulundan üniversiteye, kursa kadar.',
    seoTitle: 'Eğitim Yönetim Sistemi — Öğrenci, Sınav, Veli Portalı | kooza',
    seoDescription: 'Dershane, kurs, anaokulu, dil okulu için öğrenci kayıt, online sınav, devam takibi, veli portalı, taksit. Ücretsiz demo.',
    order: 4,
  },
  {
    slug: 'ik',
    name: 'İnsan Kaynakları',
    tagline: 'Personel, bordro, izin, mesai, performans, işe alım — KOBİ\'den orta ölçeğe tam İK çözümü.',
    heroBadge: 'İnsan Kaynakları Çözümü',
    heroTitle: 'İK süreçlerinizi\ntek panelde yönetin',
    heroSubtitle: 'Personel kart, bordro, izin, mesai, performans, işe alım — Excel ve kağıt yerine tek modern sistem. Çalışan kendi kendini yönetir, yönetici stratejik kararlara odaklanır.',
    icon: 'Users',
    iconColor: '#0891b2',
    bgColor: '#ecfeff',
    problems: [
      { title: 'Personel bilgileri Excel\'de, dosyalarda dağınık', description: 'Sözleşme, sertifika, izin geçmişi — bulmak saatler alıyor.', icon: 'FolderX' },
      { title: 'İzin talepleri WhatsApp/mail ile karışıyor', description: 'Kim ne kadar izinli, hangi tarihte — belirsiz.', icon: 'CalendarX' },
      { title: 'Bordro hesabı el ile, hata payı yüksek', description: 'SGK + GV + AGİ + kesintiler — her ay risk.', icon: 'Calculator' },
      { title: 'Performans değerlendirmesi yıllık ve sübjektif', description: 'Hedefler net değil, geri bildirim geç geliyor.', icon: 'TrendingDown' },
    ],
    features: [
      { title: 'Personel Özlük Yönetimi', description: 'Kişisel bilgi, sözleşme, sertifika, sicil — tek dijital dosya.', icon: 'IdCard' },
      { title: 'İzin & Mesai Yönetimi', description: 'Çalışan online izin ister, yönetici tek tıkla onaylar. Mesai PDKS entegre.', icon: 'CalendarCheck' },
      { title: 'Bordro & Maaş Hesaplama', description: 'SGK, GV, AGİ, kesintiler otomatik. Toplu maaş ödemesi.', icon: 'DollarSign' },
      { title: 'Performans & Hedef Yönetimi', description: 'OKR, KPI, 360° değerlendirme, periyodik geri bildirim.', icon: 'Target' },
      { title: 'İşe Alım (ATS)', description: 'İlan, başvuru, mülakat, onay süreci — adımları yönetin.', icon: 'UserPlus' },
      { title: 'Çalışan Self-Servis Portalı', description: 'Bordro, izin, sertifika — çalışan kendi yönetir.', icon: 'Smartphone' },
    ],
    benefits: [
      { label: 'İK süreç hızı', value: '4×', description: 'Otomasyonla manuel iş azalır.' },
      { label: 'Bordro hata oranı', value: '~%0', description: 'Otomatik hesap ile risk biter.' },
      { label: 'Çalışan memnuniyeti', value: '+%29', description: 'Self-servis ile.' },
      { label: 'İK\'ya gelen talep', value: '-%55', description: 'Çalışan portaldan halleder.' },
    ],
    modules: [
      { name: 'Özlük Dosyası', description: 'Tüm bilgi tek profilde.' },
      { name: 'İzin & Mesai', description: 'Online talep, PDKS.' },
      { name: 'Bordro', description: 'SGK, GV, AGİ otomatik.' },
      { name: 'Performans', description: 'OKR, KPI, 360°.' },
      { name: 'İşe Alım', description: 'ATS, mülakat süreci.' },
      { name: 'Çalışan Portalı', description: 'Self-servis web/mobil.' },
    ],
    faqs: [
      { question: 'Mevcut bordro programımdan veri taşıyabilir misiniz?', answer: 'Evet. Logo, Mikro, Netsis, Excel — tümünden veri taşıyoruz.' },
      { question: 'PDKS cihazımla entegre mi?', answer: 'Evet. ZK, Hugin, Perkotek dahil tüm yaygın PDKS markalarıyla entegre.' },
      { question: 'Bordro modülü Türk mevzuatına uygun mu?', answer: 'Evet. SGK, GV, AGİ, asgari ücret değişiklikleri otomatik güncellenir.' },
      { question: 'KVKK çalışan verisi için uygun mu?', answer: 'Tamamen. Şifreli yedek, rol-bazlı erişim, veri silme talebi otomasyonu.' },
    ],
    ctaTitle: 'İK\'yı dijitalleştirelim',
    ctaSubtitle: '5 personelden 5000\'e — büyüklüğünüze göre paket. Ücretsiz demo.',
    seoTitle: 'İnsan Kaynakları Yazılımı — Bordro, İzin, Performans | kooza',
    seoDescription: 'KOBİ ve orta ölçek için bordro, izin, mesai, performans, işe alım, self-servis portal. KVKK uyumlu. Ücretsiz demo.',
    order: 5,
  },
  {
    slug: 'web',
    name: 'Web Sitesi & E-Ticaret',
    tagline: 'Kurumsal web sitesi, blog, e-ticaret, landing page — SEO uyumlu, hızlı, mobil-öncelikli.',
    heroBadge: 'Web & Dijital Vitrin',
    heroTitle: 'Şirketinizi internette\nprofesyonelce temsil edin',
    heroSubtitle: 'Kurumsal site, e-ticaret, blog, landing page — modern tasarım, hızlı teknoloji, SEO uyumlu. Admin\'den her şeyi siz yönetin, biz teknik tarafı çözelim.',
    icon: 'Globe',
    iconColor: '#714B67',
    bgColor: '#f7f2f5',
    problems: [
      { title: 'Eski site mobilde berbat, Google\'da bulunmuyor', description: 'Müşteri telefondan girince çıkıyor, yeni müşteri gelmiyor.', icon: 'Smartphone' },
      { title: 'Her küçük değişiklik için ajansa para ödüyorsunuz', description: 'Telefon değişikliği bile ücretli, içerik güncellemesi gecikiyor.', icon: 'CreditCard' },
      { title: 'E-ticaret istiyorsunuz ama büyük platformlar pahalı', description: 'Komisyon, sabit ücret, kendi markanız öne çıkmıyor.', icon: 'ShoppingBag' },
      { title: 'Form gelse haberiniz olmuyor, lead kaçıyor', description: 'CRM yok, e-postaya düşen formlar unutuluyor.', icon: 'MailX' },
    ],
    features: [
      { title: 'Modern & Hızlı Web Sitesi', description: 'Next.js / React tabanlı, 90+ Google PageSpeed skoru, mobil-öncelikli.', icon: 'Zap' },
      { title: 'Admin Panel — Her şey sizde', description: 'İçerik, görsel, menü, blog, ürün — kod bilmeden tek tıkla düzenleyin.', icon: 'Settings' },
      { title: 'E-Ticaret Modülü', description: 'Ürün, sepet, ödeme (Iyzico/PayTR), kargo, kupon — kendi mağazanız.', icon: 'ShoppingCart' },
      { title: 'SEO & Google Optimize', description: 'Schema.org, sitemap, meta yönetimi, AMP, hız optimize.', icon: 'Search' },
      { title: 'Form & Lead → CRM', description: 'Site formu otomatik CRM\'e düşer, e-posta + SMS bildirimi.', icon: 'Inbox' },
      { title: 'Blog & İçerik Pazarlama', description: 'SEO uyumlu blog, kategori, etiket, otomatik sitemap.', icon: 'PenLine' },
    ],
    benefits: [
      { label: 'Google sıralaması', value: '+8 sıra', description: 'Ortalama ilk 6 ayda.' },
      { label: 'Mobil hız (PageSpeed)', value: '90+', description: 'Tipik 30-50\'den.' },
      { label: 'Form → satış dönüşümü', value: '+%40', description: 'CRM otomasyonu ile.' },
      { label: 'Aylık içerik maliyeti', value: '-%70', description: 'Admin\'den kendi yönetin.' },
    ],
    modules: [
      { name: 'Kurumsal Site', description: 'Hakkımızda, hizmet, iletişim.' },
      { name: 'Blog & Haber', description: 'SEO uyumlu içerik.' },
      { name: 'E-Ticaret', description: 'Ürün, sepet, ödeme, kargo.' },
      { name: 'Landing Page', description: 'Kampanya, lead toplama.' },
      { name: 'Form & CRM', description: 'Otomatik lead toplama.' },
      { name: 'Admin Paneli', description: 'Her şey siz kontrolde.' },
    ],
    faqs: [
      { question: 'Mevcut sitemi yenileyebilir misiniz?', answer: 'Evet. Tasarım yenileme, teknoloji geçişi, içerik taşıma — hepsi dahil.' },
      { question: 'Domain ve hosting de sizde mi?', answer: 'Tercihinize göre. Bizim hostingimizde olabilir veya kendi domain/hostinginizi kullanabiliriz.' },
      { question: 'Yıllık bakım ücreti var mı?', answer: 'Hosting + güncelleme + destek için aylık sabit ücret. Sürpriz fatura yok.' },
      { question: 'E-ticaret komisyonu alıyor musunuz?', answer: 'Hayır. Komisyon yok, satış sınırı yok — sadece sistem ücreti.' },
    ],
    ctaTitle: 'Web sitenizi yenileyelim',
    ctaSubtitle: 'Tek sayfadan e-ticarete — ihtiyacınıza göre çözüm. Ücretsiz tasarım önerisi.',
    seoTitle: 'Kurumsal Web Sitesi & E-Ticaret Tasarımı | kooza',
    seoDescription: 'Modern, hızlı, SEO uyumlu kurumsal web sitesi ve e-ticaret. Admin\'den siz yönetin, ücretsiz tasarım önerisi alın.',
    order: 6,
  },
]

async function run() {
  await prisma.sectorSolution.deleteMany()
  for (const s of sectors) {
    await prisma.sectorSolution.create({ data: s as any })
  }
  console.log(`✅ ${sectors.length} sektör çözümü oluşturuldu`)
  await prisma.$disconnect()
}

run().catch((e) => { console.error(e); process.exit(1) })
