/**
 * 10 kooza ürününü Product table'a seed et
 * Her ürün için: ana bilgiler + 3 paket + features
 */
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const PRODUCTS = [
  {
    slug: 'randevu',
    name: 'kooza Randevu',
    tagline: 'Randevular kelebek hızında, sektörünüze özel',
    description: 'Klinik, kuaför, fizyoterapi, masaj, spor salonu, veteriner ve tüm sektörel hizmet işletmeleri için randevu, müşteri ve finans yönetim platformu.',
    icon: '📅',
    badge: 'CANLI',
    demoUrl: 'https://randevu.kooza.tr',
    price: 299,
    features: [
      'Online randevu takvimi',
      'WhatsApp + SMS otomatik hatırlatma',
      '10 sektörel preset (klinik, kuaför, fizyo, vet vb.)',
      'Müşteri kartları + geçmiş',
      'Çoklu personel + şube',
      'Online ödeme entegre',
      'Mobilde PWA (uygulama gibi)',
      'KVKK uyumlu raporlama',
    ],
    screenshots: [],
    order: 1,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'egitim',
    name: 'kooza Eğitim',
    tagline: 'Dershane, kurs ve eğitim merkezleri için tek panel',
    description: 'Öğrenci kayıt, ders programı, sınav, devam takibi, veli portalı ve faturalandırma. Dershane, etüt merkezi, dil okulu ve özel kurslar için.',
    icon: '🎓',
    badge: 'CANLI',
    demoUrl: 'https://egitim.kooza.tr',
    price: 999,
    features: [
      'Öğrenci ve veli yönetimi',
      'Ders programı + öğretmen ataması',
      'Online sınav modülü',
      'Devam-devamsızlık takibi',
      'Veli portalı (notlar + duyurular)',
      'WhatsApp veli iletişimi',
      'e-Fatura entegre',
      'Çoklu şube',
    ],
    screenshots: [],
    order: 2,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'mesken',
    name: 'kooza Mesken',
    tagline: 'Site, apartman ve toplu konut yönetimi',
    description: 'Aidat takibi, sakin yönetimi, talep, muhasebe, raporlama. Site yöneticisi ve yönetim firmaları için modern, KVKK uyumlu platform.',
    icon: '🏘️',
    badge: 'CANLI',
    demoUrl: 'https://mesken.kooza.tr',
    price: 499,
    features: [
      'Aidat tahsilat + otomasyon',
      'Sakin/kiracı yönetimi',
      'Online talep takip sistemi',
      'Muhasebe + e-fatura',
      'WhatsApp duyuru',
      'Çoklu blok / site yönetimi',
      'Karar defteri dijital',
      'Yöneticiler için raporlama',
    ],
    screenshots: [],
    order: 3,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'tamir',
    name: 'kooza Tamir',
    tagline: 'Saha hizmet ve teknik servis yönetimi',
    description: 'Beyaz eşya, IT, klima, telefon, asansör ve tüm teknik servis sektörleri için iş emri, müşteri, parça stoğu ve teknisyen yönetimi.',
    icon: '🔧',
    badge: 'CANLI',
    demoUrl: 'https://tamir.kooza.tr',
    price: 399,
    features: [
      'İş emri + ön-arıza takibi',
      'Müşteri + cihaz geçmişi',
      'Parça stok yönetimi',
      'Teknisyen rota planlama',
      '8 sektörel preset (beyaz eşya, IT, klima vb.)',
      'WhatsApp müşteri bilgilendirme',
      'Garanti takibi',
      'Servis raporları PDF',
    ],
    screenshots: [],
    order: 4,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'hukuk',
    name: 'kooza Hukuk',
    tagline: 'Avukat ve hukuk büroları için tam yönetim',
    description: 'Müvekkil, dava, duruşma, belge, saat takibi ve faturalama. Solo avukatlar ve büyük hukuk büroları için KVKK + UYAP uyumlu.',
    icon: '⚖️',
    badge: 'CANLI',
    demoUrl: 'https://hukuk.kooza.tr',
    price: 799,
    features: [
      'Müvekkil yönetimi (gerçek + tüzel)',
      'Dava + duruşma takvimi',
      'UYAP entegrasyonu',
      'Belge dijital arşiv',
      'Saatlik çalışma takibi',
      'Faturalama (saat × ücret)',
      'Avukat-ortak ortaklık modeli',
      'KVKK uyumlu güvenli depolama',
    ],
    screenshots: [],
    order: 5,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'insaat',
    name: 'kooza İnşaat',
    tagline: 'Müteahhit, taşeron ve şantiye yönetimi',
    description: 'Proje, ihale, hakediş, şantiye, malzeme, taşeron, daire/satış. Müteahhit firmaları için end-to-end yönetim platformu.',
    icon: '🏗️',
    badge: 'CANLI',
    demoUrl: 'https://insaat.kooza.tr',
    price: 999,
    features: [
      'İhale + teklif yönetimi',
      'Hakediş + taşeron ödeme',
      'Şantiye fotoğraf + log',
      'Malzeme stok takibi',
      'Daire satış + rezervasyon',
      'Bakanlık birim fiyat pozları',
      'Çevre ve Şehircilik uyumlu',
      'Personel puantaj',
    ],
    screenshots: [],
    order: 6,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'emlak',
    name: 'kooza Emlak',
    tagline: 'Gayrimenkul ofisleri için akıllı CRM',
    description: 'İlan, müşteri, lead, satış, sözleşme, komisyon. AI destekli fiyat tahmini, çoklu portal entegrasyonu, WhatsApp Business.',
    icon: '🏠',
    badge: 'CANLI',
    demoUrl: 'https://emlak.kooza.tr',
    price: 599,
    features: [
      'Otomatik ilan portali entegre (Hepsiemlak, sahibinden)',
      'Müşteri + lead yönetimi',
      'AI fiyat tahmini',
      'Komisyon paylaşımı',
      'WhatsApp Business entegre',
      'Sözleşme + e-imza',
      'Çoklu danışman + şube',
      'Ev sahibi/kiracı arşivi',
    ],
    screenshots: [],
    order: 7,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'servis',
    name: 'kooza Servis',
    tagline: 'Restoran, kafe ve hızlı servis için POS',
    description: 'Adisyon, masa yönetimi, kasa, kurye, mutfak ekranı, garson sipariş. Tek panel restoran/kafe POS sistemi.',
    icon: '🍽️',
    badge: 'BETA',
    demoUrl: 'https://servis.kooza.tr/demo',
    price: 599,
    features: [
      'Masa adisyon + sipariş',
      'Garson tablet/telefon',
      'Mutfak ekranı (KDS)',
      'Kasa + günsonu raporu',
      'Kurye entegrasyonu',
      'Yemek Sepeti, Trendyol entegre',
      'Stok + reçete takibi',
      'Müşteri sadakat puanı',
    ],
    screenshots: [],
    order: 8,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'muhasebe',
    name: 'kooza Muhasebe',
    tagline: 'KOBİ\'ler için ön muhasebe + e-fatura',
    description: 'e-Fatura, e-Arşiv, cari, banka, çek-senet, gelir-gider. GİB entegre, Türkiye için optimize edilmiş ön muhasebe.',
    icon: '💰',
    badge: 'CANLI',
    demoUrl: 'https://muhasebe.kooza.tr',
    price: 599,
    features: [
      'e-Fatura, e-Arşiv (GİB entegre)',
      'Cari hesap + ekstre',
      'Banka entegrasyonu',
      'Çek-senet takibi',
      'Gelir-gider raporu',
      'Stok + ürün yönetimi',
      'KDV beyanname',
      'AI destekli kategorileme',
    ],
    screenshots: [],
    order: 9,
    status: 'ACTIVE' as const,
  },
  {
    slug: 'ik',
    name: 'kooza İK',
    tagline: 'Personel, bordro, izin yönetimi',
    description: 'İşe alım, personel, bordro, izin, mesai, performans. KVKK + iş kanunu uyumlu, Türkiye için tasarlanmış.',
    icon: '👥',
    badge: 'BETA',
    demoUrl: 'https://ik.kooza.tr',
    price: 499,
    features: [
      'Personel kart + özlük dosyası',
      'Bordro hesaplama',
      'İzin + mesai yönetimi',
      'PDKS giriş-çıkış',
      'Performans değerlendirme',
      'İşe alım pipeline',
      'KEP + e-tebligat',
      'SGK + İŞKUR entegre',
    ],
    screenshots: [],
    order: 10,
    status: 'ACTIVE' as const,
  },
]

async function main() {
  console.log('🌱 10 ürün seed başlıyor...')
  for (const product of PRODUCTS) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
    console.log(`  ✓ ${product.icon} ${product.name}`)
  }
  console.log('🎉 10 ürün başarıyla seed edildi!')
}

main()
  .catch((e) => {
    console.error('❌ Hata:', e.message)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
